/*
 * SPDX-License-Identifier: BSD-3-Clause
 * SPDX-FileCopyrightText: 2025 Z-Wave-Alliance <https://z-wavealliance.org/>
 */
/**
 * @file cc_version_migration_config.h
 * @note !!! THIS FILE IS AUTOGENERATED BY `generate_configurations.py` !!! DO NOT MODIFY !!!
 */

#ifndef _CC_VERSION_MIGRATION_CONFIG_H_
#define _CC_VERSION_MIGRATION_CONFIG_H_

/**
 * \defgroup configuration Configuration
 * Configuration
 *
 * \addtogroup configuration
 * @{
 */
/**
 * \defgroup command_class_version_migration_configuration Configuration for Version v4+ migration operations
 * Configuration for Version v4+ migration operations
 *
 * \addtogroup command_class_version_migration_configuration
 * @{
 */

/**
 * Maximum number of migration operations that can be supported by the end node <1..3:1>
 *
 * This needs to be as small as possible to encompass the needs of the node - this value defines some under-the-hood buffers and such and can contribute to bloat. Note that this is NOT the value reported to the controller, that is a dynamic value determined at runtime based on which operations are reported. 
 */
#if !defined(CC_VERSION_MAX_NUM_MIGRATION_OPERATIONS_SUPPORTED)
#define CC_VERSION_MAX_NUM_MIGRATION_OPERATIONS_SUPPORTED  2
#endif /* !defined(CC_VERSION_MAX_NUM_MIGRATION_OPERATIONS_SUPPORTED) */

/**
 * Enable migration operations on the end node
 *
 */
#if !defined(CC_VERSION_MIGRATION_SUPPORTED)
#define CC_VERSION_MIGRATION_SUPPORTED  0
#endif /* !defined(CC_VERSION_MIGRATION_SUPPORTED) */

/**
 * Enable migration of Users and PIN codes to User Codes
 *
 * To be used when a newer end node with existing Users needs to be retrofitted into an older Z-Wave network that only supports User Code v1/v2. Both User Code and User Credential CCs must be supported in the NIF.
 */
#if !defined(CC_VERSION_ENABLE_MIGRATION_U3C_TO_USER_CODE)
#define CC_VERSION_ENABLE_MIGRATION_U3C_TO_USER_CODE  0
#endif /* !defined(CC_VERSION_ENABLE_MIGRATION_U3C_TO_USER_CODE) */

/**
 * Enable migration of User Codes to Users and PIN codes to be used by newer controllers
 *
 * To be used when a older end node with existing User Codes is installed in a new network or receives a firmware update enabling User Credential v2. Both User Code and User Credential CCs must be supported in the NIF.
 */
#if !defined(CC_VERSION_ENABLE_MIGRATION_USER_CODE_TO_U3C)
#define CC_VERSION_ENABLE_MIGRATION_USER_CODE_TO_U3C  0
#endif /* !defined(CC_VERSION_ENABLE_MIGRATION_USER_CODE_TO_U3C) */

/**@}*/ /* \addtogroup command_class_version_migration_configuration */

/**@}*/ /* \addtogroup configuration */
#endif /* _CC_VERSION_MIGRATION_CONFIG_H_ */
